### ISSUE TITLE
Issue in DLM.py and also a question

### ISSUE THREAD

**Issue by MechaFear** [tulip-lab/open-code#1]
Hi, I opened this issue because executing **Eval.py** gives me the following error:

> Traceback (most recent call last):
>   File "Eval.py", line 117, in <module>
>     valuelist = walk_forward(train_X,train_Y,test_X, test_Y,grid_search,scaler)
>   File "Eval.py", line 30, in walk_forward
>     model = build_model(history_x,history_y,lstm_unit=x[0],drop_rate=x[1],dense_unit=x[2],batch_size=x[3],epochs=x[4])
>   File "/mnt/c/Users/User/Desktop/UniUD/LabAI/open-code-master/DLM/DLM.py", line 45, in build_model
>     dense_unit)
>   File "/mnt/c/Users/User/Desktop/UniUD/LabAI/open-code-master/DLM/DLM.py", line 27, in model_attention_applied_before_lstm
>     attention_mul = attention_block(inputs,TIME_STEPS,INPUT_DIM)
>   File "/mnt/c/Users/User/Desktop/UniUD/LabAI/open-code-master/DLM/DLM.py", line 21, in attention_block
>     output_attention_mul = merge([inputs, a_probs], name='attention_mul', mode='mul')
> TypeError: 'module' object is not callable

Upon a closer code inspection I figured out what the problem was:
line 21 of DLM.py 
>     output_attention_mul = merge([inputs, a_probs], name='attention_mul', mode='mul')

constains _merge_, a layer not implemented in more recent versions of Keras.

I tried changing that line to
>     output_attention_mul = Multiply()([inputs, a_probs])
and now the code seems to work.  Could you please confirm whether my fix is valid or not?

I also have a question concerning **Setting.py**: since I'm trying to recreate the results of your paper _"Tourism demand forecasting - A deep learning approach"_ can I please know which were the actual settings used to get the values in the tables 2,3,4 and 6,7,8 or the article?

**Comment by xhan97** [comment]
1. In the 21 line of DLM.py, the merge layer is actually a concatenate operation, not a multiply layer.  It has been removed from Keras 2.0. You should find a substitute in Keras 2.0 or use the Keras 1.X.

2. The Setting.py is the default initial parameter sets file. The result showed in our paper is got from this default parameter sets.  In each step of walk-forward, a set of the best parameters is selected from this file by grid search. Moreover, the weights of the neural network are highly depending on the initialization.
