### ISSUE TITLE
Predictivity Data and Code finalize

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/open-code#3]
Finalize the information for the data or code, corresponding to the published paper.

**Comment by chriszhangpodo** [comment]
open code info has been updated in develop branch, PR review is needed for approval

**Comment by tuliplab** [comment]
@chriszhangpodo you directly has the write permission. There is no need to pull request, which is for people outside the tulip, but want to contribute to tulip repo.

Please also check the root readme file's doi links, and the detailed code link.

**Comment by tuliplab** [comment]
@chriszhangpodo 
please check whether this issue can be closed. You can pull request for futher code.
